# Hello Numpy

Introduction to NUMPY


In [ ]:
import numpy as np

## List vs. Numpy Array

A list is a Python data structure.

A Numpy array is an N-dimensional tensor. It can be a vector, a matrix, or a higher-order tensor. The elements of a tensor have the same type.

A list can be converted to a Numpy array.

In [2]:
# This is a simple list
listItems = [1, 2, 3, 4, 5]
print('List contains {} items: {}'.format(len(listItems), listItems))


List contains 5 items: [1, 2, 3, 4, 5]


In [3]:
# List can also contain elements of different types
listItems2 = [0, 1.0, True, 'StringItem', {"x": "1.0"} ]
print(listItems2)


[0, 1.0, True, 'StringItem', {'x': '1.0'}]


Let's try to create a matrix M using a list - it's actually two nested lists.

In [4]:
M = [[1,2,3], [4,5,6], [7,8,9]]
print(M)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


It is difficult to express the dimensions of such a matrix exactly. Each nested list can have a different size....

### <b>A list is not a suitable data structure for working with matrices. !</b>

## Numpy Arrays


In [ ]:
# Let's create a numpy array - it looks like a list
a = np.array([1, 2, 3, 4])
print('Numpy array: ', a)
print('Element type: ', a.dtype)
print('Shape: ', a.shape)


Numpy array:  [1 2 3 4]
Element type:  int64
Shape:  (4,)


Shape: (4,) = RANK 1 


In [ ]:
# Let's try to make a matrix.
m = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
print('Numpy array: \n', m)
print('Element type: ', m.dtype)
print('Shape: ', m.shape)


Numpy array: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Element type:  float64
Shape:  (3, 3)


Shape: (3, 3) = RANK 2       Two-dimensional matrix.

All the calculations we will do in these examples will involve RANK 2 arrays.
RANK 1 is something we will want to avoid.

We will also use vectors - column or row - as RANK 2 arrays.

In [ ]:
# Let's try to make a row vector
v = np.array([[1, 2, 3, 4]], dtype=float)
print('Shape: ', v.shape)
print(v)
print('')

# Let's make it a Transposed - Column Vector
v = v.T
print('Transposed shape: ', v.shape)
print(v)


Shape:  (1, 4)
[[1. 2. 3. 4.]]

Transposed shape:  (4, 1)
[[1.]
 [2.]
 [3.]
 [4.]]


## Cut of a matrix

Cut lowers Rank!

In [ ]:
# Let's make a 3x3 matrix
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m)
print('Shape: ',m.shape)   # >> (3, 3)
print('')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)



In [ ]:
# second row

r = m[1,:]    # >> (3, ) Rank 1
print('Second row - Rank 1:')
print(r)
print(r.shape)
print('')

r = m[1,None]   # >> (1, 3) Rank 2
print('Second row - Rank 2:')
print(r)
print(r.shape)
print('')


Druhy riadok - Rank 1:
[4 5 6]
(3,)

Druhy riadok - Rank 2:
[[4 5 6]]
(1, 3)



In [ ]:
# Second column

c = m[:,1]    # >> (3, ) Rank 1
print('Second column - Rank 1:')
print(c)
print(c.shape)
print('')

c = m[:,1,None]   # >> (3, 1) Rank 2
print('Second column - Rank 2:')
print(c)
print(c.shape)


Druhy stlpec - Rank 1:
[2 5 8]
(3,)

Druhy stlpec - Rank 2:
[[2]
 [5]
 [8]]
(3, 1)


## Broadcasting

If we are trying to perform a matrix operation on operands with an unsuitable shape, Numpy can help by meaningfully duplicating values.

In [ ]:
# Let's make a matrix M - 2x2, and a scalar b
M = np.array([[1,2], [3,4]])     # >> (2, 2)
b = 1

print('Matrix M: \n', M, '\n')
print('b: \n', b, '\n')
print('Matrix M+b: \n', M+b, '\n')


Matrix M: 
 [[1 2]
 [3 4]] 

b: 
 1 

Matrix M+b: 
 [[2 3]
 [4 5]] 



In [ ]:
# Let's create a row vector c - 1x2
c = np.array([[5, 5]])           # >> (1, 2)

print('Matrix M: \n', M, '\n')
print('c: \n', c, '\n')
print('Matrix M+c: \n', M+c, '\n')

Matrix M: 
 [[1 2]
 [3 4]] 

c: 
 [[5 5]] 

Matrix M+c: 
 [[6 7]
 [8 9]] 



In [ ]:
# Let's create a column vector d - 2x1
d = np.array([[10], [10]])  # >> (2, 1)

print('Matrix M: \n', M, '\n')
print('d: \n', d, '\n')
print('Matrix M+d: \n', M+d, '\n')


Matrix M: 
 [[1 2]
 [3 4]] 

d: 
 [[10]
 [10]] 

Matrix M+d: 
 [[11 12]
 [13 14]] 



## Functions over Numpy array

The Numpy library can perform mathematical functions on matrix elements. For example, exp.

In [ ]:
import math

In [ ]:
# We call the traditional math.exp function
a = -1.0
print(math.exp(a))


0.36787944117144233


In [ ]:
# We call the numpy.exp function
a = np.array([[-1.0, 0, 1.0]], dtype=float)
r = np.exp(a)

print('a: \n', a, '\n')
print('r: \n', r, '\n')


a: 
 [[-1.  0.  1.]] 

r: 
 [[0.36787944 1.         2.71828183]] 



In [17]:
# Boolean arraye
a = np.arange(start=0, stop=10, step=1, dtype=int)
print('a: \n', a, '\n')

# Element-wise porovnanie
b = (a > 5)
print('b: \n', b, '\n')


a: 
 [0 1 2 3 4 5 6 7 8 9] 

b: 
 [False False False False False False  True  True  True  True] 



## Initialization

We can initialize matrices either to a specific value - 0, 1.
Or randomly from a distribution (uniform, normal, ... )

In [ ]:
# We initialize all elements to the value 1
v = np.ones(shape=(5, 10), dtype=float)
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# We initialize all elements to the value 0
v = np.zeros(shape=(5, 10), dtype=float)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Initialize with the same shape
v2 = np.ones_like(v)
print(v2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# Initialization with random values ​​- Uniform Distribution
v = np.random.rand(2, 3)    # <0; 1>
print(v)
print(v.shape)

[[0.78846939 0.45312891 0.73789241]
 [0.60690046 0.48092421 0.59970727]]
(2, 3)


In [ ]:
# Initialization with random values ​​- Normal Distribution
v = np.random.randn(2, 3)   # Normal(mean=0, stddev=1)
print(v)
print(v.shape)

[[-0.34745991 -0.99997096  0.45799493]
 [-0.83502909 -0.44754944  1.26640687]]
(2, 3)
